### ISSUE TITLE
DEVELOP 05: Domain Modeling

### ISSUE THREAD

**Issue by jerry914** [SOA-02/YoutubeAPITest#24]
## Task

- [x] Update the description of your project
- [x] Create the domain objects you might need
- [x] Develop your Web Application
- [x] Deploy your Web application to Heroku (AWS)

## RuboCop/Code Smell Offenses

Some minor RuboCop offenses were found in `app/controllers/app.rb`. 

Please also resolve these issues:
- **Avoid commenting out code**: Consider removing unused code as comments to keep your files clean. Note, Git version control helps you to retrieve any deleted code if needed!

Great job so far—you're on the right track!

**Comment by soumyaray** [comment]
Please rename this repo right away to the name of your app – not about testing youtube's API!

**Comment by soumyaray** [comment]
Hey folks, your entities are completely missing any real business logic – can we have a chat about what/where your value add is?  Remember that you should not just be making an app that acts as a front-end to someone else's API!
